### ISSUE TITLE
Google plus access token.

### ISSUE THREAD

**Issue by dowsanjack** [SiddharthaRRamesh/ionic-starter-oauth#6]
Hello,

First of all a big thanks for this. Really, was absolutely stuck, before this :+1: 

I just wanted to know, when I'm logging through G+ or FB, i m not getting any token. Though [ngCordova](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/facebook.js#L54) has a get token but cant find any such for G+.

My JSON response after a successful login is:

```
ageRangeMin:  
displayName: 
email: 
familyName: 
gender: 
givenName: 
imageUrl:
userId: 
```

Any help would be appreciated.

**Comment by srameshr** [comment]
Glad you found this helpful!

Yeah, so a ouath token is basically a temporary key, that can be used for a specific time interval as described by the oauth provider. 

In this scenario you don't need the oauth token itself because you wont be querying for the google+ api after you get the initial user data. I think that is the reason why the plugin author (@EddyVerbruggen) has removed it from the response. At least that is what I think.

Can I close this now?
